login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^signin/',views.sign_in,name='sign_in'),
	url(r'^logout/',views.logout_user,name='logout'),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^basic/',views.basic,name='basic'),
	url(r'^details/(?P<qu_id>[0-9]+)/',views.details,name = 'details'),
	url(r'^result/(?P<que_id>\d+)/',views.results,name = 'results'),
	url(r'^vote/(?P<que_id>\d+)/',views.vote,name = 'vote'),
]

tempProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^',include('myapp.urls',namespace='myapps')),
    url(r'^login/',include('login.urls',namespace='login')),
	url(r'^polls/',include('polls.urls',namespace='polls')),
	url(r'^login_error/',views.login_error,name="login_error"),
    url(r'^admin/', admin.site.urls),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class questions(models.Model):
	question_text = models.CharField(max_length=200)
	published = models.DateTimeField('date_published')

	def publish_it(self):
		self.published = timezone.now()
		self.save()
	
	def __str__(self):
		return self.question_text


class choice(models.Model):
	question = models.ForeignKey(questions,on_delete = models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
# Create your views here.

def index(request):
	return(render(request,'polls/index.html',{}))
	# return(HttpResponse("<h1><center>welcome to polls app</h1></center>"))

def basic(request):
	latest_ques = questions.objects.filter(published__lte = timezone.now()).order_by('published')
	data_fr_page = {"Questions" : latest_ques}
	return(render(request,'polls/basic.html',data_fr_page))

def details(request,qu_id):
	return(render(request,'polls/details.html',{"id":qu_id}))

def results(request):
	return(render(request,'polls/results.html',{}))

def vote(request,q_id):
	return(HttpResponse("<center><h1>U voted for- %s </h1></center>"%(q_id)))

polls/templates/polls/basic.html
<html>
	<head>
		<title>
			Lists all questions
		</title>
	</head>
	<body>
		<center>
			<h1>
				HERE's THE LIST OF ALL QUESTIONS!!
			</h1>
		</center>
		<br><br><br>
		{% for question in Questions %}
		<div>
			<h2>
				<a href="{% url 'polls:details' question.id %}">
					Question = {{question.question_text}} <br>
				</a>
				Q_ID = {{question.id}}<br>
				publish_date = {{question.published}} <br><br>
			</h2>
			<br>
			<br>
		</div>
		{% endfor %}

	</body>
</html>

polls/templates/polls/details.html
<html>
	<head>
		<title>
			Details page of a particular question
		</title>
	</head>
	<body>
		<h1>
			you selected question {{id}}
		</h1>
	</body>
</html>

polls/templates/polls/index.html
<html>
	<head>
		<title>
			INDEX PAGE OF POLLS
		</title>
	</head>
	<body>
		<center>
			<h1>
				here is waht you can do- 
			</h1>
		</center>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<div>
			<center>
				<h2>
					<a href='/polls/basic'>
						basic
					</a>
				</h2>
			</center>
		</div>
		<div>
			<center>
				<h2>
					<a href='/login'>
						login
					</a>
				</h2>
			</center>
		</div>
	</body>
</html>